version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - jabawack81
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.12.0
    - 1.12.1
    - 1.9.0
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
  - dependency-name: puma
    versions:
    - 5.2.0
  - dependency-name: capybara
    versions:
    - 3.35.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - jabawack81
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.445.0
    - 1.447.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.459.0
    - 1.471.0
    - 1.474.0
    - 1.476.0
    - 1.478.0
    - 1.483.0
    - 1.486.0
    - 1.489.0
    - 1.491.0
    - 1.495.0
    - 1.500.0
    - 1.503.0
    - 1.505.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.518.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.531.0
    - 1.532.0
    - 1.538.0
    - 1.557.0
    - 1.563.0
    - 1.566.0
    - 1.570.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
